Imports System
Imports System.Collections.Generic
Imports System.Text.RegularExpressions

''' <summary>
''' Represents a parsed system log event or notification message.
''' </summary>
Public Class LogEvent
    ''' <summary>
    ''' The extracted notification code (e.g. "HHC02279I", "IEE305I", "$HASP373", etc.)
    ''' </summary>
    Public Property NotificationCode As String

    ''' <summary>
    ''' The full raw log line text.
    ''' </summary>
    Public Property RawMessage As String

    ''' <summary>
    ''' Timestamp or prefix if parsed from the log line.
    ''' </summary>
    Public Property Timestamp As DateTime?

    Public Sub New(notificationCode As String, rawMessage As String)
        Me.NotificationCode = notificationCode
        Me.RawMessage = rawMessage
        Me.Timestamp = DateTime.Now
    End Sub
End Class

''' <summary>
''' Framework for listening to and processing system log events, error messages, and operator requests.
''' </summary>
Public Class SystemLogEventHandler
    ''' <summary>
    ''' Regex pattern matching Hercules (e.g. HHC02279I), MVS/OS operator/error message codes (e.g. IEE305I, IEA995I, $HASP373, IEC141I).
    ''' </summary>
    Private Shared ReadOnly EventCodeRegex As New Regex("\b([A-Z]{3,4}\d{3,5}[A-Z]|\$[A-Z0-9]{3,7})\b", RegexOptions.Compiled)

    ''' <summary>
    ''' Event raised when a system log message containing a notification code is processed.
    ''' </summary>
    Public Event LogEventReceived As EventHandler(Of LogEvent)

    ''' <summary>
    ''' Processes incoming log lines, extracts notification codes, and fires events.
    ''' Currently displays / outputs the notification code as a placeholder for future expanding logic.
    ''' </summary>
    ''' <param name="logLines">Collection of raw log lines to process.</param>
    Public Sub ProcessLogLines(logLines As IEnumerable(Of String))
        If logLines Is Nothing Then Return

        For Each line In logLines
            If String.IsNullOrWhiteSpace(line) Then Continue For

            Dim match = EventCodeRegex.Match(line)
            Dim code = If(match.Success, match.Value, "UNKNOWN")
            Dim evt As New LogEvent(code, line)

            ' Framework handler action
            OnLogEventDetected(evt)
        Next
    End Sub

    ''' <summary>
    ''' Executes a REXX script file (.rexx, .rex) passing the log event code and message as parameters,
    ''' returning output strings ready to be sent back to Hercules across platforms.
    ''' </summary>
    ''' <param name="scriptPath">Path to the .rexx / .rex file.</param>
    ''' <param name="evt">The LogEvent containing notification code and raw line.</param>
    ''' <returns>Collection of command strings generated by the REXX script.</returns>
    Public Async Function ExecuteScriptAndGetCommandAsync(scriptPath As String, evt As LogEvent) As Task(Of List(Of String))
        Dim params As New List(Of String) From {
            evt.NotificationCode,
            evt.RawMessage
        }
        Return Await RexxRunner.ExecuteScriptAsync(scriptPath, params)
    End Function

    ''' <summary>
    ''' Path to the master REXX handler script.
    ''' </summary>
    Public Property MasterScriptPath As String = System.IO.Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "ScriptData", "MasterLogHandler.rex")

    ''' <summary>
    ''' Executes the master REXX script for a log event, passing event code and full log line.
    ''' </summary>
    ''' <param name="evt">Log event containing notification code and raw message.</param>
    ''' <returns>Collection of Hercules command responses returned by the REXX script.</returns>
    Public Async Function ProcessEventWithMasterScriptAsync(evt As LogEvent) As Task(Of List(Of String))
        If Not System.IO.File.Exists(MasterScriptPath) Then
            Return New List(Of String)()
        End If

        Return Await ExecuteScriptAndGetCommandAsync(MasterScriptPath, evt)
    End Function

    ''' <summary>
    ''' Responds to a single detected log event. Currently prints/displays the notification code.
    ''' </summary>
    Protected Overridable Sub OnLogEventDetected(e As LogEvent)
        ' Placeholder response action: display the notification code
        Console.WriteLine($"[SystemLogEvent Framework] Notification Code Detected: {e.NotificationCode}")

        ' Raise event for external subscribers
        RaiseEvent LogEventReceived(Me, e)
    End Sub
End Class
