Imports System
Imports System.Collections.Generic
Imports System.Text.RegularExpressions

''' <summary>
''' Represents a parsed system log event or notification message.
''' </summary>
Public Class LogEvent
    ''' <summary>
    ''' The extracted notification code (e.g. "HHC02279I", "IEE305I", "$HASP373", etc.)
    ''' </summary>
    Public Property NotificationCode As String

    ''' <summary>
    ''' The full raw log line text.
    ''' </summary>
    Public Property RawMessage As String

    ''' <summary>
    ''' Timestamp or prefix if parsed from the log line.
    ''' </summary>
    Public Property Timestamp As DateTime?

    Public Sub New(notificationCode As String, rawMessage As String)
        Me.NotificationCode = notificationCode
        Me.RawMessage = rawMessage
        Me.Timestamp = DateTime.Now
    End Sub
End Class

''' <summary>
''' Framework for listening to and processing system log events, error messages, and operator requests.
''' </summary>
Public Class SystemLogEventHandler
    ''' <summary>
    ''' Regex pattern matching Hercules (e.g. HHC02279I), MVS/OS operator/error message codes (e.g. IRB101I, IEE305I, IEA995I, $HASP373, IEC141I),
    ''' and VM operating system Control Program / CMS / RSCS message codes (e.g. HCPMSG001I, HCPLOG045E, HCPMNT020E, DMSITP143E, DMTNXS100I).
    ''' </summary>
    Public Shared ReadOnly EventCodeRegex As New Regex("\b([A-Z]{2,7}\d{3,5}[A-Z]{0,2}|\$[A-Z0-9]{3,7})\b", RegexOptions.Compiled)

    ''' <summary>
    ''' Event raised when a system log message containing a notification code is processed.
    ''' </summary>
    Public Event LogEventReceived As EventHandler(Of LogEvent)

    ''' <summary>
    ''' Processes incoming log lines, extracts notification codes, and fires events.
    ''' </summary>
    ''' <param name="logLines">Collection of raw log lines to process.</param>
    Public Sub ProcessLogLines(logLines As IEnumerable(Of String))
        If logLines Is Nothing Then Return

        For Each line In logLines
            If String.IsNullOrWhiteSpace(line) Then Continue For

            Dim match = EventCodeRegex.Match(line)
            Dim code = If(match.Success, match.Value, "UNKNOWN")

            ' Suppress Hercules informational message echoes (HHC01603I) to prevent infinite loop recursion
            If code.Equals("HHC01603I", StringComparison.OrdinalIgnoreCase) Then Continue For

            Dim evt As New LogEvent(code, line)

            ' Framework handler action
            OnLogEventDetected(evt)
        Next
    End Sub

    ''' <summary>
    ''' Asynchronously processes incoming log lines, extracts notification codes, fires events,
    ''' executes the master REXX script for recognized log events, and returns all generated Hercules commands.
    ''' </summary>
    ''' <param name="logLines">Collection of raw log lines to process.</param>
    ''' <param name="logHandler">Optional callback to receive REXX execution diagnostic messages.</param>
    ''' <returns>List of Hercules command strings produced by REXX scripts for the processed log lines.</returns>
    Public Async Function ProcessLogLinesAsync(logLines As IEnumerable(Of String), Optional logHandler As Action(Of String) = Nothing) As Task(Of List(Of String))
        Dim allCommands As New List(Of String)()
        If logLines Is Nothing Then Return allCommands

        For Each line In logLines
            If String.IsNullOrWhiteSpace(line) Then Continue For

            Dim match = EventCodeRegex.Match(line)
            Dim code = If(match.Success, match.Value, "UNKNOWN")

            ' Suppress Hercules informational message echoes (HHC01603I) to prevent infinite loop recursion
            If code.Equals("HHC01603I", StringComparison.OrdinalIgnoreCase) Then Continue For

            Dim evt As New LogEvent(code, line)

            ' Framework handler action & event raising
            OnLogEventDetected(evt)

            ' Execute master REXX script for this event
            Dim commands = Await ProcessEventWithMasterScriptAsync(evt, logHandler)
            If commands IsNot Nothing AndAlso commands.Count > 0 Then
                allCommands.AddRange(commands)
            End If
        Next

        Return allCommands
    End Function

    ''' <summary>
    ''' Executes a REXX script file (.rexx, .rex) passing the log event code and message as parameters,
    ''' returning output strings ready to be sent back to Hercules across platforms.
    ''' </summary>
    ''' <param name="scriptPath">Path to the .rexx / .rex file.</param>
    ''' <param name="evt">The LogEvent containing notification code and raw line.</param>
    ''' <param name="logHandler">Optional callback action to receive diagnostic/security messages.</param>
    ''' <returns>Collection of command strings generated by the REXX script.</returns>
    Public Async Function ExecuteScriptAndGetCommandAsync(scriptPath As String, evt As LogEvent, Optional logHandler As Action(Of String) = Nothing) As Task(Of List(Of String))
        Dim params As New List(Of String) From {
            evt.NotificationCode,
            evt.RawMessage
        }
        Return Await RexxRunner.ExecuteScriptAsync(scriptPath, params, 5, logHandler)
    End Function

    Private Shared Function GetDefaultMasterScriptPath() As String
        Dim envScript = Environment.GetEnvironmentVariable("HYPERION_REXX_SCRIPT")
        If Not String.IsNullOrWhiteSpace(envScript) Then
            Return System.IO.Path.GetFullPath(envScript.Trim())
        End If
        Return System.IO.Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "ScriptData", "MasterLogHandler.rex")
    End Function

    Private _masterScriptPath As String = GetDefaultMasterScriptPath()

    ''' <summary>
    ''' Path to the master REXX handler script. Configurable via HYPERION_REXX_SCRIPT environment variable or --script CLI argument.
    ''' </summary>
    Public Property MasterScriptPath As String
        Get
            Return _masterScriptPath
        End Get
        Set(value As String)
            _masterScriptPath = value
            If Not String.IsNullOrWhiteSpace(value) Then
                Dim dir = System.IO.Path.GetDirectoryName(value)
                If Not String.IsNullOrWhiteSpace(dir) AndAlso System.IO.Directory.Exists(dir) Then
                    RexxSecurityValidator.AllowedWorkingDirectory = dir
                End If
            End If
        End Set
    End Property

    ''' <summary>
    ''' Executes the master REXX script for a log event, passing event code and full log line.
    ''' </summary>
    ''' <param name="evt">Log event containing notification code and raw message.</param>
    ''' <param name="logHandler">Optional callback to receive diagnostic output messages.</param>
    ''' <returns>Collection of Hercules command responses returned by the REXX script.</returns>
    Public Async Function ProcessEventWithMasterScriptAsync(evt As LogEvent, Optional logHandler As Action(Of String) = Nothing) As Task(Of List(Of String))
        If Not System.IO.File.Exists(MasterScriptPath) Then
            If logHandler IsNot Nothing Then
                logHandler($"[REXX Warning] Master script file not found: {MasterScriptPath}")
            End If
            Return New List(Of String)()
        End If

        Return Await ExecuteScriptAndGetCommandAsync(MasterScriptPath, evt, logHandler)
    End Function

    ''' <summary>
    ''' Responds to a single detected log event. Currently prints/displays the notification code.
    ''' </summary>
    Protected Overridable Sub OnLogEventDetected(e As LogEvent)
        ' Raise event for external subscribers
        RaiseEvent LogEventReceived(Me, e)
    End Sub
End Class
